Featget cover fees
neptune-mutual/app-v2 pull request #65
Opened 2022-01-17 02:44 UTC by savinnpm

2022-01-17 04:48 UTC, flashburst requested changes

2022-01-17 04:48 UTC, flashburst commented on src/components/UI/organisms/PolicyFeesAndExpiry/PolicyFeesAndExpiry.jsx
> +    console.log(monthNames[(date.getMonth() + claimEnd - 1) % 12]);
Remove console.log

2022-01-17 04:48 UTC, flashburst commented on src/components/UI/organisms/cover-form/index.jsx
> +      console.info("--------------------------------------");
Remove console.info (s)

2022-01-17 05:07 UTC, savinnpm commented on src/components/UI/organisms/PolicyFeesAndExpiry/PolicyFeesAndExpiry.jsx
> +    console.log(monthNames[(date.getMonth() + claimEnd - 1) % 12]);
done

2022-01-17 05:07 UTC, savinnpm commented on src/components/UI/organisms/cover-form/index.jsx
> +      console.info("--------------------------------------");
completed

2022-01-18 02:09 UTC, flashburst approved these changes

2022-01-18 02:09 UTC, merged